name: Bug report
description: Detailed specification for the bug
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Issue description
      description: A clear and concise description of what the bug is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: References & additional context
      description: Add any links or other context about the problem here.
      placeholder: |
        - Loom:
        - Logrocket:
        - Discord:
    validations:
      required: false
