name: Feature spec
description: Detailed description of what needs to be implemented
labels: [feature]
body:
  - type: textarea
    attributes:
      label: User story
      description: A clear and concise description of the feature
    validations:
      required: false
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: List of deliverables or conditions for completion
      placeholder: |
        - I want to see ABC when I click XYZ
        - When user does XYZ, the app should do ABC
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context & Dependencies
      description: Some additional context about the feature or the problem
    validations:
      required: false
  - type: textarea
    attributes:
      label: References
      description: Add any links with explanations or related discussions
      placeholder: |
        - Loom:
        - Logrocket:
        - Discord:
    validations:
      required: false
