name: Code Quality
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - run: pip install --upgrade pip
    - run: pip install black isort[colors] flake8
    - run: black --line-length=131 --check --diff --color .
    - run: isort --line-length=131 --check --diff --color .
    - run: flake8 .
